services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:${ES_PORT}:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "curl -s --cacert config/certs/http_ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'"]
      interval: 10s
      timeout: 10s
      retries: 60

  kib01:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    ports:
      - "127.0.0.1:${KIBANA_PORT}:5601"
    volumes:
      - kibanaconfig:/usr/share/kibana/config
      - kibanadata:/usr/share/kibana/data
    depends_on:
      es01:
        condition: service_healthy

volumes:
  esdata01:
  kibanaconfig:
  kibanadata:
